### PR TITLE
test: fix them

### PR DESCRIPTION
**Pull request by fippo**
another attempt at fixing the tests

### CODE REVIEW

**Comment by fippo** [comment]
since @manasdpradhan asked... this shows a real problem in Firefox actually.

**Comment by fippo** [comment]
so the issue is that the test calls removeStream in Firefox. Which does not exist. It seems to fail independent of rtcstats (i.e. when I remove rtcstats from the testpage.html file) but for reasons I don't understand this passes in adapter (and now here again).

I mangled things not to attempt wrapping removeStream. In general the checks for wrapping something need to be conditional on the existence of the native method. But after this is merged :-)

**Review by manasdpradhan — APPROVED** [review]
LGTM. Brownie points for not allowing failures on Firefox beta :) 

Does someone manually need to keep upgrading the drivers every few weeks?

**Comment by fippo** [comment]
we ran into issues with both chromedriver and geckodriver on adapter recently so had to pin them :-/

**Pull request merged**
