### PR TITLE
UPDATE to latest version of adapter for testing

### PR DESCRIPTION
**Pull request by ggarber**

### CODE REVIEW

**Comment by fippo** [comment]
odd, you seem to have more / different success than I had in #37?

**Comment by ggarber** [comment]
shit, i didn't see you already had a PR for this

**Review by fippo — APPROVED** [review]
i don't see why that code would fail. OTOH your code is more robust

**Comment by ggarber** [comment]
because JSON.parse(JSON.stringify(undefined)) fails

**Comment by fippo** [comment]
Oh. I fixed that in https://github.com/webrtc/adapter/pull/407 so maybe we just need to retry once that is merged?

**Comment by fippo** [comment]
ah. You don't use this together with adapter?

**Comment by fippo** [comment]
I think you're running into the test issue that Firefox is not using marionette

**Comment by fippo** [comment]
locally things work again at least!

**Pull request merged**
