### PR TITLE
addTransciever from nils-ohlmeier jitsi fork

### PR DESCRIPTION
**Pull request by misi**
based on https://github.com/jitsi/rtcstats/commit/7d3061c52a5f84a02e3e1f55525ec799c2e63944

### CODE REVIEW

**Comment by misi** [comment]
@fippo I am wondering what did I wrong? Why you closed it so fast without any comment? Did I miss sg?

**Comment by fippo** [comment]
Ask Oyvind...

**Comment by misi** [comment]
Thanks for the answer. Sorry and now I understood..

**Comment by balazskreith** [comment]
I see a very mature and adult approach to resolving your personal disagreements.

**Comment by fippo** [comment]
mind you that this copy-paste didn't even work...

**Pull request closed without merging**
